# Generated by Django 4.1.4 on 2022-12-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_account_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('interval', models.IntegerField()),
                ('added_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
