# Generated by Django 4.1.4 on 2022-12-21 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_urlmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.urlmodel')),
            ],
        ),
    ]
