# Generated by Django 4.1.4 on 2022-12-22 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_hello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlstatus',
            name='is_active',
        ),
        migrations.AddField(
            model_name='urlstatus',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='urlstatus',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlstatus',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.urlmodel'),
        ),
    ]
