# Generated by Django 4.1.4 on 2022-12-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorrequest',
            name='response_time',
            field=models.DateTimeField(),
        ),
    ]
