# Generated by Django 4.1.4 on 2022-12-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_alter_monitorrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorrequest',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='monitorrequest',
            name='response_status',
            field=models.CharField(max_length=50),
        ),
    ]
