# Generated by Django 4.1.4 on 2022-12-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0005_alter_monitorrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorrequest',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
