# Generated by Django 4.1.4 on 2022-12-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0006_monitorrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
            ],
        ),
    ]
